#!/bin/env python

from subprocess import run, PIPE
from shutil import which
from pathlib import Path

DBUS_CODEGEN = which('dbus-codegen-rust') or ''

dir = Path(__file__).parent.resolve()

input_dir  = dir / 'dbus_xml'
output_dir = dir / 'src/dbus_codegen'

def main():

    files = list(input_dir.glob('*.xml'))

    for f in files:
        print(f'f: {f}')

        xml      = f.read_bytes()
        filename = output_dir / f'{f.stem}.rs'

        p = run([DBUS_CODEGEN], input=xml, stdout=PIPE)

        rust = p.stdout

        _ = filename.write_bytes(rust)

    mod = output_dir / 'mod.rs'

    _ = mod.write_text('\n'.join([
        '// autogenerated by codegen.py',
        '',
        '#![allow(dead_code)]',
        '',
        *[
            f'pub mod {f.stem};'
            for f in files

        ]
    ]))




if __name__ == '__main__':
    main()
