// This code was autogenerated with `dbus-codegen-rust `, see https://github.com/diwic/dbus-rs
use dbus as dbus;
#[allow(unused_imports)]
use dbus::arg;
use dbus::blocking;

pub trait OrgKdeKonsoleWindow {
    fn session_count(&self) -> Result<i32, dbus::Error>;
    fn session_list(&self) -> Result<Vec<String>, dbus::Error>;
    fn current_session(&self) -> Result<i32, dbus::Error>;
    fn set_current_session(&self, session_id: i32) -> Result<(), dbus::Error>;
    fn new_session(&self) -> Result<i32, dbus::Error>;
    fn new_session_(&self, profile: &str) -> Result<i32, dbus::Error>;
    fn new_session__(&self, profile: &str, directory: &str) -> Result<i32, dbus::Error>;
    fn default_profile(&self) -> Result<String, dbus::Error>;
    fn set_default_profile(&self, profile: &str) -> Result<(), dbus::Error>;
    fn profile_list(&self) -> Result<Vec<String>, dbus::Error>;
    fn next_session(&self) -> Result<(), dbus::Error>;
    fn prev_session(&self) -> Result<(), dbus::Error>;
    fn move_session_left(&self) -> Result<(), dbus::Error>;
    fn move_session_right(&self) -> Result<(), dbus::Error>;
    fn set_tab_width_to_text(&self, arg0: bool) -> Result<(), dbus::Error>;
    fn save_layout_file(&self) -> Result<(), dbus::Error>;
    fn load_layout_file(&self) -> Result<(), dbus::Error>;
    fn load_layout(&self, file: &str) -> Result<(), dbus::Error>;
    fn view_hierarchy(&self) -> Result<Vec<String>, dbus::Error>;
    fn get_split_proportions(&self, splitter_id: i32) -> Result<Vec<f64>, dbus::Error>;
    fn create_split(&self, view_id: i32, horizontal_split: bool) -> Result<bool, dbus::Error>;
    fn create_split_with_existing(&self, target_splitter_id: i32, widget_infos: Vec<&str>, idx: i32, horizontal_split: bool) -> Result<bool, dbus::Error>;
    fn set_current_view(&self, view_id: i32) -> Result<bool, dbus::Error>;
    fn resize_splits(&self, splitter_id: i32, percentages: Vec<f64>) -> Result<bool, dbus::Error>;
    fn move_splitter(&self, splitter_id: i32, target_splitter_id: i32, idx: i32) -> Result<bool, dbus::Error>;
    fn move_view(&self, view_id: i32, target_splitter_id: i32, idx: i32) -> Result<bool, dbus::Error>;
}

impl<'a, T: blocking::BlockingSender, C: ::std::ops::Deref<Target=T>> OrgKdeKonsoleWindow for blocking::Proxy<'a, C> {

    fn session_count(&self) -> Result<i32, dbus::Error> {
        self.method_call("org.kde.konsole.Window", "sessionCount", ())
            .and_then(|r: (i32, )| Ok(r.0, ))
    }

    fn session_list(&self) -> Result<Vec<String>, dbus::Error> {
        self.method_call("org.kde.konsole.Window", "sessionList", ())
            .and_then(|r: (Vec<String>, )| Ok(r.0, ))
    }

    fn current_session(&self) -> Result<i32, dbus::Error> {
        self.method_call("org.kde.konsole.Window", "currentSession", ())
            .and_then(|r: (i32, )| Ok(r.0, ))
    }

    fn set_current_session(&self, session_id: i32) -> Result<(), dbus::Error> {
        self.method_call("org.kde.konsole.Window", "setCurrentSession", (session_id, ))
    }

    fn new_session(&self) -> Result<i32, dbus::Error> {
        self.method_call("org.kde.konsole.Window", "newSession", ())
            .and_then(|r: (i32, )| Ok(r.0, ))
    }

    fn new_session_(&self, profile: &str) -> Result<i32, dbus::Error> {
        self.method_call("org.kde.konsole.Window", "newSession", (profile, ))
            .and_then(|r: (i32, )| Ok(r.0, ))
    }

    fn new_session__(&self, profile: &str, directory: &str) -> Result<i32, dbus::Error> {
        self.method_call("org.kde.konsole.Window", "newSession", (profile, directory, ))
            .and_then(|r: (i32, )| Ok(r.0, ))
    }

    fn default_profile(&self) -> Result<String, dbus::Error> {
        self.method_call("org.kde.konsole.Window", "defaultProfile", ())
            .and_then(|r: (String, )| Ok(r.0, ))
    }

    fn set_default_profile(&self, profile: &str) -> Result<(), dbus::Error> {
        self.method_call("org.kde.konsole.Window", "setDefaultProfile", (profile, ))
    }

    fn profile_list(&self) -> Result<Vec<String>, dbus::Error> {
        self.method_call("org.kde.konsole.Window", "profileList", ())
            .and_then(|r: (Vec<String>, )| Ok(r.0, ))
    }

    fn next_session(&self) -> Result<(), dbus::Error> {
        self.method_call("org.kde.konsole.Window", "nextSession", ())
    }

    fn prev_session(&self) -> Result<(), dbus::Error> {
        self.method_call("org.kde.konsole.Window", "prevSession", ())
    }

    fn move_session_left(&self) -> Result<(), dbus::Error> {
        self.method_call("org.kde.konsole.Window", "moveSessionLeft", ())
    }

    fn move_session_right(&self) -> Result<(), dbus::Error> {
        self.method_call("org.kde.konsole.Window", "moveSessionRight", ())
    }

    fn set_tab_width_to_text(&self, arg0: bool) -> Result<(), dbus::Error> {
        self.method_call("org.kde.konsole.Window", "setTabWidthToText", (arg0, ))
    }

    fn save_layout_file(&self) -> Result<(), dbus::Error> {
        self.method_call("org.kde.konsole.Window", "saveLayoutFile", ())
    }

    fn load_layout_file(&self) -> Result<(), dbus::Error> {
        self.method_call("org.kde.konsole.Window", "loadLayoutFile", ())
    }

    fn load_layout(&self, file: &str) -> Result<(), dbus::Error> {
        self.method_call("org.kde.konsole.Window", "loadLayout", (file, ))
    }

    fn view_hierarchy(&self) -> Result<Vec<String>, dbus::Error> {
        self.method_call("org.kde.konsole.Window", "viewHierarchy", ())
            .and_then(|r: (Vec<String>, )| Ok(r.0, ))
    }

    fn get_split_proportions(&self, splitter_id: i32) -> Result<Vec<f64>, dbus::Error> {
        self.method_call("org.kde.konsole.Window", "getSplitProportions", (splitter_id, ))
            .and_then(|r: (Vec<f64>, )| Ok(r.0, ))
    }

    fn create_split(&self, view_id: i32, horizontal_split: bool) -> Result<bool, dbus::Error> {
        self.method_call("org.kde.konsole.Window", "createSplit", (view_id, horizontal_split, ))
            .and_then(|r: (bool, )| Ok(r.0, ))
    }

    fn create_split_with_existing(&self, target_splitter_id: i32, widget_infos: Vec<&str>, idx: i32, horizontal_split: bool) -> Result<bool, dbus::Error> {
        self.method_call("org.kde.konsole.Window", "createSplitWithExisting", (target_splitter_id, widget_infos, idx, horizontal_split, ))
            .and_then(|r: (bool, )| Ok(r.0, ))
    }

    fn set_current_view(&self, view_id: i32) -> Result<bool, dbus::Error> {
        self.method_call("org.kde.konsole.Window", "setCurrentView", (view_id, ))
            .and_then(|r: (bool, )| Ok(r.0, ))
    }

    fn resize_splits(&self, splitter_id: i32, percentages: Vec<f64>) -> Result<bool, dbus::Error> {
        self.method_call("org.kde.konsole.Window", "resizeSplits", (splitter_id, percentages, ))
            .and_then(|r: (bool, )| Ok(r.0, ))
    }

    fn move_splitter(&self, splitter_id: i32, target_splitter_id: i32, idx: i32) -> Result<bool, dbus::Error> {
        self.method_call("org.kde.konsole.Window", "moveSplitter", (splitter_id, target_splitter_id, idx, ))
            .and_then(|r: (bool, )| Ok(r.0, ))
    }

    fn move_view(&self, view_id: i32, target_splitter_id: i32, idx: i32) -> Result<bool, dbus::Error> {
        self.method_call("org.kde.konsole.Window", "moveView", (view_id, target_splitter_id, idx, ))
            .and_then(|r: (bool, )| Ok(r.0, ))
    }
}

pub trait OrgFreedesktopDBusProperties {
    fn get(&self, interface_name: &str, property_name: &str) -> Result<arg::Variant<Box<dyn arg::RefArg + 'static>>, dbus::Error>;
    fn set(&self, interface_name: &str, property_name: &str, value: arg::Variant<Box<dyn arg::RefArg>>) -> Result<(), dbus::Error>;
    fn get_all(&self, interface_name: &str) -> Result<arg::PropMap, dbus::Error>;
}

#[derive(Debug)]
pub struct OrgFreedesktopDBusPropertiesPropertiesChanged {
    pub interface_name: String,
    pub changed_properties: arg::PropMap,
    pub invalidated_properties: Vec<String>,
}

impl arg::AppendAll for OrgFreedesktopDBusPropertiesPropertiesChanged {
    fn append(&self, i: &mut arg::IterAppend) {
        arg::RefArg::append(&self.interface_name, i);
        arg::RefArg::append(&self.changed_properties, i);
        arg::RefArg::append(&self.invalidated_properties, i);
    }
}

impl arg::ReadAll for OrgFreedesktopDBusPropertiesPropertiesChanged {
    fn read(i: &mut arg::Iter) -> Result<Self, arg::TypeMismatchError> {
        Ok(OrgFreedesktopDBusPropertiesPropertiesChanged {
            interface_name: i.read()?,
            changed_properties: i.read()?,
            invalidated_properties: i.read()?,
        })
    }
}

impl dbus::message::SignalArgs for OrgFreedesktopDBusPropertiesPropertiesChanged {
    const NAME: &'static str = "PropertiesChanged";
    const INTERFACE: &'static str = "org.freedesktop.DBus.Properties";
}

impl<'a, T: blocking::BlockingSender, C: ::std::ops::Deref<Target=T>> OrgFreedesktopDBusProperties for blocking::Proxy<'a, C> {

    fn get(&self, interface_name: &str, property_name: &str) -> Result<arg::Variant<Box<dyn arg::RefArg + 'static>>, dbus::Error> {
        self.method_call("org.freedesktop.DBus.Properties", "Get", (interface_name, property_name, ))
            .and_then(|r: (arg::Variant<Box<dyn arg::RefArg + 'static>>, )| Ok(r.0, ))
    }

    fn set(&self, interface_name: &str, property_name: &str, value: arg::Variant<Box<dyn arg::RefArg>>) -> Result<(), dbus::Error> {
        self.method_call("org.freedesktop.DBus.Properties", "Set", (interface_name, property_name, value, ))
    }

    fn get_all(&self, interface_name: &str) -> Result<arg::PropMap, dbus::Error> {
        self.method_call("org.freedesktop.DBus.Properties", "GetAll", (interface_name, ))
            .and_then(|r: (arg::PropMap, )| Ok(r.0, ))
    }
}

pub trait OrgFreedesktopDBusIntrospectable {
    fn introspect(&self) -> Result<String, dbus::Error>;
}

impl<'a, T: blocking::BlockingSender, C: ::std::ops::Deref<Target=T>> OrgFreedesktopDBusIntrospectable for blocking::Proxy<'a, C> {

    fn introspect(&self) -> Result<String, dbus::Error> {
        self.method_call("org.freedesktop.DBus.Introspectable", "Introspect", ())
            .and_then(|r: (String, )| Ok(r.0, ))
    }
}

pub trait OrgFreedesktopDBusPeer {
    fn ping(&self) -> Result<(), dbus::Error>;
    fn get_machine_id(&self) -> Result<String, dbus::Error>;
}

impl<'a, T: blocking::BlockingSender, C: ::std::ops::Deref<Target=T>> OrgFreedesktopDBusPeer for blocking::Proxy<'a, C> {

    fn ping(&self) -> Result<(), dbus::Error> {
        self.method_call("org.freedesktop.DBus.Peer", "Ping", ())
    }

    fn get_machine_id(&self) -> Result<String, dbus::Error> {
        self.method_call("org.freedesktop.DBus.Peer", "GetMachineId", ())
            .and_then(|r: (String, )| Ok(r.0, ))
    }
}
