// This code was autogenerated with `dbus-codegen-rust `, see https://github.com/diwic/dbus-rs
use dbus as dbus;
#[allow(unused_imports)]
use dbus::arg;
use dbus::blocking;

pub trait OrgKdeKonsoleKonsoleMainWindow {
    fn view_full_screen(&self, full_screen: bool) -> Result<(), dbus::Error>;
}

impl<'a, T: blocking::BlockingSender, C: ::std::ops::Deref<Target=T>> OrgKdeKonsoleKonsoleMainWindow for blocking::Proxy<'a, C> {

    fn view_full_screen(&self, full_screen: bool) -> Result<(), dbus::Error> {
        self.method_call("org.kde.konsole.Konsole.MainWindow", "viewFullScreen", (full_screen, ))
    }
}

pub trait OrgKdeKonsoleKXmlGuiWindow {
    fn configure_toolbars(&self) -> Result<(), dbus::Error>;
    fn slot_state_changed(&self, newstate: &str) -> Result<(), dbus::Error>;
    fn slot_state_changed_(&self, newstate: &str, reverse: bool) -> Result<(), dbus::Error>;
    fn is_tool_bar_visible(&self, name: &str) -> Result<bool, dbus::Error>;
    fn set_tool_bar_visible(&self, name: &str, visible: bool) -> Result<(), dbus::Error>;
    fn has_menu_bar(&self) -> Result<bool, dbus::Error>;
    fn auto_save_settings(&self) -> Result<bool, dbus::Error>;
    fn auto_save_group(&self) -> Result<String, dbus::Error>;
    fn standard_tool_bar_menu_enabled(&self) -> Result<bool, dbus::Error>;
    fn setstandard_tool_bar_menu_enabled(&self, value: bool) -> Result<(), dbus::Error>;
    fn tool_bars(&self) -> Result<Vec<String>, dbus::Error>;
}

impl<'a, T: blocking::BlockingSender, C: ::std::ops::Deref<Target=T>> OrgKdeKonsoleKXmlGuiWindow for blocking::Proxy<'a, C> {

    fn configure_toolbars(&self) -> Result<(), dbus::Error> {
        self.method_call("org.kde.konsole.KXmlGuiWindow", "configureToolbars", ())
    }

    fn slot_state_changed(&self, newstate: &str) -> Result<(), dbus::Error> {
        self.method_call("org.kde.konsole.KXmlGuiWindow", "slotStateChanged", (newstate, ))
    }

    fn slot_state_changed_(&self, newstate: &str, reverse: bool) -> Result<(), dbus::Error> {
        self.method_call("org.kde.konsole.KXmlGuiWindow", "slotStateChanged", (newstate, reverse, ))
    }

    fn is_tool_bar_visible(&self, name: &str) -> Result<bool, dbus::Error> {
        self.method_call("org.kde.konsole.KXmlGuiWindow", "isToolBarVisible", (name, ))
            .and_then(|r: (bool, )| Ok(r.0, ))
    }

    fn set_tool_bar_visible(&self, name: &str, visible: bool) -> Result<(), dbus::Error> {
        self.method_call("org.kde.konsole.KXmlGuiWindow", "setToolBarVisible", (name, visible, ))
    }

    fn has_menu_bar(&self) -> Result<bool, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(self, "org.kde.konsole.KXmlGuiWindow", "hasMenuBar")
    }

    fn auto_save_settings(&self) -> Result<bool, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(self, "org.kde.konsole.KXmlGuiWindow", "autoSaveSettings")
    }

    fn auto_save_group(&self) -> Result<String, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(self, "org.kde.konsole.KXmlGuiWindow", "autoSaveGroup")
    }

    fn standard_tool_bar_menu_enabled(&self) -> Result<bool, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(self, "org.kde.konsole.KXmlGuiWindow", "standardToolBarMenuEnabled")
    }

    fn tool_bars(&self) -> Result<Vec<String>, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(self, "org.kde.konsole.KXmlGuiWindow", "toolBars")
    }

    fn setstandard_tool_bar_menu_enabled(&self, value: bool) -> Result<(), dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::set(self, "org.kde.konsole.KXmlGuiWindow", "standardToolBarMenuEnabled", value)
    }
}

pub trait OrgKdeKonsoleKMainWindow {
    fn set_caption(&self, caption: &str) -> Result<(), dbus::Error>;
    fn set_caption_(&self, caption: &str, modified: bool) -> Result<(), dbus::Error>;
    fn set_plain_caption(&self, caption: &str) -> Result<(), dbus::Error>;
    fn app_help_activated(&self) -> Result<(), dbus::Error>;
    fn set_settings_dirty(&self) -> Result<(), dbus::Error>;
    fn has_menu_bar(&self) -> Result<bool, dbus::Error>;
    fn auto_save_settings(&self) -> Result<bool, dbus::Error>;
    fn auto_save_group(&self) -> Result<String, dbus::Error>;
}

impl<'a, T: blocking::BlockingSender, C: ::std::ops::Deref<Target=T>> OrgKdeKonsoleKMainWindow for blocking::Proxy<'a, C> {

    fn set_caption(&self, caption: &str) -> Result<(), dbus::Error> {
        self.method_call("org.kde.konsole.KMainWindow", "setCaption", (caption, ))
    }

    fn set_caption_(&self, caption: &str, modified: bool) -> Result<(), dbus::Error> {
        self.method_call("org.kde.konsole.KMainWindow", "setCaption", (caption, modified, ))
    }

    fn set_plain_caption(&self, caption: &str) -> Result<(), dbus::Error> {
        self.method_call("org.kde.konsole.KMainWindow", "setPlainCaption", (caption, ))
    }

    fn app_help_activated(&self) -> Result<(), dbus::Error> {
        self.method_call("org.kde.konsole.KMainWindow", "appHelpActivated", ())
    }

    fn set_settings_dirty(&self) -> Result<(), dbus::Error> {
        self.method_call("org.kde.konsole.KMainWindow", "setSettingsDirty", ())
    }

    fn has_menu_bar(&self) -> Result<bool, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(self, "org.kde.konsole.KMainWindow", "hasMenuBar")
    }

    fn auto_save_settings(&self) -> Result<bool, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(self, "org.kde.konsole.KMainWindow", "autoSaveSettings")
    }

    fn auto_save_group(&self) -> Result<String, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(self, "org.kde.konsole.KMainWindow", "autoSaveGroup")
    }
}

pub trait OrgQtprojectQtQMainWindow {
    fn set_animated(&self, enabled: bool) -> Result<(), dbus::Error>;
    fn set_dock_nesting_enabled(&self, enabled: bool) -> Result<(), dbus::Error>;
    fn set_unified_title_and_tool_bar_on_mac(&self, set: bool) -> Result<(), dbus::Error>;
    fn icon_size(&self) -> Result<(i32, i32,), dbus::Error>;
    fn seticon_size(&self, value: (i32, i32,)) -> Result<(), dbus::Error>;
    fn animated(&self) -> Result<bool, dbus::Error>;
    fn setanimated(&self, value: bool) -> Result<(), dbus::Error>;
    fn document_mode(&self) -> Result<bool, dbus::Error>;
    fn setdocument_mode(&self, value: bool) -> Result<(), dbus::Error>;
    fn dock_nesting_enabled(&self) -> Result<bool, dbus::Error>;
    fn setdock_nesting_enabled(&self, value: bool) -> Result<(), dbus::Error>;
    fn unified_title_and_tool_bar_on_mac(&self) -> Result<bool, dbus::Error>;
    fn setunified_title_and_tool_bar_on_mac(&self, value: bool) -> Result<(), dbus::Error>;
}

impl<'a, T: blocking::BlockingSender, C: ::std::ops::Deref<Target=T>> OrgQtprojectQtQMainWindow for blocking::Proxy<'a, C> {

    fn set_animated(&self, enabled: bool) -> Result<(), dbus::Error> {
        self.method_call("org.qtproject.Qt.QMainWindow", "setAnimated", (enabled, ))
    }

    fn set_dock_nesting_enabled(&self, enabled: bool) -> Result<(), dbus::Error> {
        self.method_call("org.qtproject.Qt.QMainWindow", "setDockNestingEnabled", (enabled, ))
    }

    fn set_unified_title_and_tool_bar_on_mac(&self, set: bool) -> Result<(), dbus::Error> {
        self.method_call("org.qtproject.Qt.QMainWindow", "setUnifiedTitleAndToolBarOnMac", (set, ))
    }

    fn icon_size(&self) -> Result<(i32, i32,), dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(self, "org.qtproject.Qt.QMainWindow", "iconSize")
    }

    fn animated(&self) -> Result<bool, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(self, "org.qtproject.Qt.QMainWindow", "animated")
    }

    fn document_mode(&self) -> Result<bool, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(self, "org.qtproject.Qt.QMainWindow", "documentMode")
    }

    fn dock_nesting_enabled(&self) -> Result<bool, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(self, "org.qtproject.Qt.QMainWindow", "dockNestingEnabled")
    }

    fn unified_title_and_tool_bar_on_mac(&self) -> Result<bool, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(self, "org.qtproject.Qt.QMainWindow", "unifiedTitleAndToolBarOnMac")
    }

    fn seticon_size(&self, value: (i32, i32,)) -> Result<(), dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::set(self, "org.qtproject.Qt.QMainWindow", "iconSize", value)
    }

    fn setanimated(&self, value: bool) -> Result<(), dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::set(self, "org.qtproject.Qt.QMainWindow", "animated", value)
    }

    fn setdocument_mode(&self, value: bool) -> Result<(), dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::set(self, "org.qtproject.Qt.QMainWindow", "documentMode", value)
    }

    fn setdock_nesting_enabled(&self, value: bool) -> Result<(), dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::set(self, "org.qtproject.Qt.QMainWindow", "dockNestingEnabled", value)
    }

    fn setunified_title_and_tool_bar_on_mac(&self, value: bool) -> Result<(), dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::set(self, "org.qtproject.Qt.QMainWindow", "unifiedTitleAndToolBarOnMac", value)
    }
}

pub trait OrgQtprojectQtQWidget {
    fn set_enabled(&self, arg0: bool) -> Result<(), dbus::Error>;
    fn set_disabled(&self, arg0: bool) -> Result<(), dbus::Error>;
    fn set_window_modified(&self, arg0: bool) -> Result<(), dbus::Error>;
    fn set_window_title(&self, arg0: &str) -> Result<(), dbus::Error>;
    fn set_style_sheet(&self, style_sheet: &str) -> Result<(), dbus::Error>;
    fn set_focus(&self) -> Result<(), dbus::Error>;
    fn update(&self) -> Result<(), dbus::Error>;
    fn repaint(&self) -> Result<(), dbus::Error>;
    fn set_visible(&self, visible: bool) -> Result<(), dbus::Error>;
    fn set_hidden(&self, hidden: bool) -> Result<(), dbus::Error>;
    fn show(&self) -> Result<(), dbus::Error>;
    fn hide(&self) -> Result<(), dbus::Error>;
    fn show_minimized(&self) -> Result<(), dbus::Error>;
    fn show_maximized(&self) -> Result<(), dbus::Error>;
    fn show_full_screen(&self) -> Result<(), dbus::Error>;
    fn show_normal(&self) -> Result<(), dbus::Error>;
    fn close(&self) -> Result<bool, dbus::Error>;
    fn raise(&self) -> Result<(), dbus::Error>;
    fn lower(&self) -> Result<(), dbus::Error>;
    fn modal(&self) -> Result<bool, dbus::Error>;
    fn enabled(&self) -> Result<bool, dbus::Error>;
    fn setenabled(&self, value: bool) -> Result<(), dbus::Error>;
    fn geometry(&self) -> Result<(i32, i32, i32, i32,), dbus::Error>;
    fn setgeometry(&self, value: (i32, i32, i32, i32,)) -> Result<(), dbus::Error>;
    fn frame_geometry(&self) -> Result<(i32, i32, i32, i32,), dbus::Error>;
    fn normal_geometry(&self) -> Result<(i32, i32, i32, i32,), dbus::Error>;
    fn x_(&self) -> Result<i32, dbus::Error>;
    fn y_(&self) -> Result<i32, dbus::Error>;
    fn pos(&self) -> Result<(i32, i32,), dbus::Error>;
    fn setpos(&self, value: (i32, i32,)) -> Result<(), dbus::Error>;
    fn frame_size(&self) -> Result<(i32, i32,), dbus::Error>;
    fn size(&self) -> Result<(i32, i32,), dbus::Error>;
    fn setsize(&self, value: (i32, i32,)) -> Result<(), dbus::Error>;
    fn width(&self) -> Result<i32, dbus::Error>;
    fn height(&self) -> Result<i32, dbus::Error>;
    fn rect(&self) -> Result<(i32, i32, i32, i32,), dbus::Error>;
    fn children_rect(&self) -> Result<(i32, i32, i32, i32,), dbus::Error>;
    fn minimum_size(&self) -> Result<(i32, i32,), dbus::Error>;
    fn setminimum_size(&self, value: (i32, i32,)) -> Result<(), dbus::Error>;
    fn maximum_size(&self) -> Result<(i32, i32,), dbus::Error>;
    fn setmaximum_size(&self, value: (i32, i32,)) -> Result<(), dbus::Error>;
    fn minimum_width(&self) -> Result<i32, dbus::Error>;
    fn setminimum_width(&self, value: i32) -> Result<(), dbus::Error>;
    fn minimum_height(&self) -> Result<i32, dbus::Error>;
    fn setminimum_height(&self, value: i32) -> Result<(), dbus::Error>;
    fn maximum_width(&self) -> Result<i32, dbus::Error>;
    fn setmaximum_width(&self, value: i32) -> Result<(), dbus::Error>;
    fn maximum_height(&self) -> Result<i32, dbus::Error>;
    fn setmaximum_height(&self, value: i32) -> Result<(), dbus::Error>;
    fn size_increment(&self) -> Result<(i32, i32,), dbus::Error>;
    fn setsize_increment(&self, value: (i32, i32,)) -> Result<(), dbus::Error>;
    fn base_size(&self) -> Result<(i32, i32,), dbus::Error>;
    fn setbase_size(&self, value: (i32, i32,)) -> Result<(), dbus::Error>;
    fn mouse_tracking(&self) -> Result<bool, dbus::Error>;
    fn setmouse_tracking(&self, value: bool) -> Result<(), dbus::Error>;
    fn tablet_tracking(&self) -> Result<bool, dbus::Error>;
    fn settablet_tracking(&self, value: bool) -> Result<(), dbus::Error>;
    fn is_active_window(&self) -> Result<bool, dbus::Error>;
    fn focus(&self) -> Result<bool, dbus::Error>;
    fn updates_enabled(&self) -> Result<bool, dbus::Error>;
    fn setupdates_enabled(&self, value: bool) -> Result<(), dbus::Error>;
    fn visible(&self) -> Result<bool, dbus::Error>;
    fn setvisible(&self, value: bool) -> Result<(), dbus::Error>;
    fn minimized(&self) -> Result<bool, dbus::Error>;
    fn maximized(&self) -> Result<bool, dbus::Error>;
    fn full_screen(&self) -> Result<bool, dbus::Error>;
    fn size_hint(&self) -> Result<(i32, i32,), dbus::Error>;
    fn minimum_size_hint(&self) -> Result<(i32, i32,), dbus::Error>;
    fn accept_drops(&self) -> Result<bool, dbus::Error>;
    fn setaccept_drops(&self, value: bool) -> Result<(), dbus::Error>;
    fn window_title(&self) -> Result<String, dbus::Error>;
    fn setwindow_title(&self, value: String) -> Result<(), dbus::Error>;
    fn window_icon_text(&self) -> Result<String, dbus::Error>;
    fn setwindow_icon_text(&self, value: String) -> Result<(), dbus::Error>;
    fn window_opacity(&self) -> Result<f64, dbus::Error>;
    fn setwindow_opacity(&self, value: f64) -> Result<(), dbus::Error>;
    fn window_modified(&self) -> Result<bool, dbus::Error>;
    fn setwindow_modified(&self, value: bool) -> Result<(), dbus::Error>;
    fn tool_tip(&self) -> Result<String, dbus::Error>;
    fn settool_tip(&self, value: String) -> Result<(), dbus::Error>;
    fn tool_tip_duration(&self) -> Result<i32, dbus::Error>;
    fn settool_tip_duration(&self, value: i32) -> Result<(), dbus::Error>;
    fn status_tip(&self) -> Result<String, dbus::Error>;
    fn setstatus_tip(&self, value: String) -> Result<(), dbus::Error>;
    fn whats_this(&self) -> Result<String, dbus::Error>;
    fn setwhats_this(&self, value: String) -> Result<(), dbus::Error>;
    fn accessible_name(&self) -> Result<String, dbus::Error>;
    fn setaccessible_name(&self, value: String) -> Result<(), dbus::Error>;
    fn accessible_description(&self) -> Result<String, dbus::Error>;
    fn setaccessible_description(&self, value: String) -> Result<(), dbus::Error>;
    fn accessible_identifier(&self) -> Result<String, dbus::Error>;
    fn setaccessible_identifier(&self, value: String) -> Result<(), dbus::Error>;
    fn auto_fill_background(&self) -> Result<bool, dbus::Error>;
    fn setauto_fill_background(&self, value: bool) -> Result<(), dbus::Error>;
    fn style_sheet(&self) -> Result<String, dbus::Error>;
    fn setstyle_sheet(&self, value: String) -> Result<(), dbus::Error>;
    fn window_file_path(&self) -> Result<String, dbus::Error>;
    fn setwindow_file_path(&self, value: String) -> Result<(), dbus::Error>;
}

impl<'a, T: blocking::BlockingSender, C: ::std::ops::Deref<Target=T>> OrgQtprojectQtQWidget for blocking::Proxy<'a, C> {

    fn set_enabled(&self, arg0: bool) -> Result<(), dbus::Error> {
        self.method_call("org.qtproject.Qt.QWidget", "setEnabled", (arg0, ))
    }

    fn set_disabled(&self, arg0: bool) -> Result<(), dbus::Error> {
        self.method_call("org.qtproject.Qt.QWidget", "setDisabled", (arg0, ))
    }

    fn set_window_modified(&self, arg0: bool) -> Result<(), dbus::Error> {
        self.method_call("org.qtproject.Qt.QWidget", "setWindowModified", (arg0, ))
    }

    fn set_window_title(&self, arg0: &str) -> Result<(), dbus::Error> {
        self.method_call("org.qtproject.Qt.QWidget", "setWindowTitle", (arg0, ))
    }

    fn set_style_sheet(&self, style_sheet: &str) -> Result<(), dbus::Error> {
        self.method_call("org.qtproject.Qt.QWidget", "setStyleSheet", (style_sheet, ))
    }

    fn set_focus(&self) -> Result<(), dbus::Error> {
        self.method_call("org.qtproject.Qt.QWidget", "setFocus", ())
    }

    fn update(&self) -> Result<(), dbus::Error> {
        self.method_call("org.qtproject.Qt.QWidget", "update", ())
    }

    fn repaint(&self) -> Result<(), dbus::Error> {
        self.method_call("org.qtproject.Qt.QWidget", "repaint", ())
    }

    fn set_visible(&self, visible: bool) -> Result<(), dbus::Error> {
        self.method_call("org.qtproject.Qt.QWidget", "setVisible", (visible, ))
    }

    fn set_hidden(&self, hidden: bool) -> Result<(), dbus::Error> {
        self.method_call("org.qtproject.Qt.QWidget", "setHidden", (hidden, ))
    }

    fn show(&self) -> Result<(), dbus::Error> {
        self.method_call("org.qtproject.Qt.QWidget", "show", ())
    }

    fn hide(&self) -> Result<(), dbus::Error> {
        self.method_call("org.qtproject.Qt.QWidget", "hide", ())
    }

    fn show_minimized(&self) -> Result<(), dbus::Error> {
        self.method_call("org.qtproject.Qt.QWidget", "showMinimized", ())
    }

    fn show_maximized(&self) -> Result<(), dbus::Error> {
        self.method_call("org.qtproject.Qt.QWidget", "showMaximized", ())
    }

    fn show_full_screen(&self) -> Result<(), dbus::Error> {
        self.method_call("org.qtproject.Qt.QWidget", "showFullScreen", ())
    }

    fn show_normal(&self) -> Result<(), dbus::Error> {
        self.method_call("org.qtproject.Qt.QWidget", "showNormal", ())
    }

    fn close(&self) -> Result<bool, dbus::Error> {
        self.method_call("org.qtproject.Qt.QWidget", "close", ())
            .and_then(|r: (bool, )| Ok(r.0, ))
    }

    fn raise(&self) -> Result<(), dbus::Error> {
        self.method_call("org.qtproject.Qt.QWidget", "raise", ())
    }

    fn lower(&self) -> Result<(), dbus::Error> {
        self.method_call("org.qtproject.Qt.QWidget", "lower", ())
    }

    fn modal(&self) -> Result<bool, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(self, "org.qtproject.Qt.QWidget", "modal")
    }

    fn enabled(&self) -> Result<bool, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(self, "org.qtproject.Qt.QWidget", "enabled")
    }

    fn geometry(&self) -> Result<(i32, i32, i32, i32,), dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(self, "org.qtproject.Qt.QWidget", "geometry")
    }

    fn frame_geometry(&self) -> Result<(i32, i32, i32, i32,), dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(self, "org.qtproject.Qt.QWidget", "frameGeometry")
    }

    fn normal_geometry(&self) -> Result<(i32, i32, i32, i32,), dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(self, "org.qtproject.Qt.QWidget", "normalGeometry")
    }

    fn x_(&self) -> Result<i32, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(self, "org.qtproject.Qt.QWidget", "x")
    }

    fn y_(&self) -> Result<i32, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(self, "org.qtproject.Qt.QWidget", "y")
    }

    fn pos(&self) -> Result<(i32, i32,), dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(self, "org.qtproject.Qt.QWidget", "pos")
    }

    fn frame_size(&self) -> Result<(i32, i32,), dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(self, "org.qtproject.Qt.QWidget", "frameSize")
    }

    fn size(&self) -> Result<(i32, i32,), dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(self, "org.qtproject.Qt.QWidget", "size")
    }

    fn width(&self) -> Result<i32, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(self, "org.qtproject.Qt.QWidget", "width")
    }

    fn height(&self) -> Result<i32, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(self, "org.qtproject.Qt.QWidget", "height")
    }

    fn rect(&self) -> Result<(i32, i32, i32, i32,), dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(self, "org.qtproject.Qt.QWidget", "rect")
    }

    fn children_rect(&self) -> Result<(i32, i32, i32, i32,), dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(self, "org.qtproject.Qt.QWidget", "childrenRect")
    }

    fn minimum_size(&self) -> Result<(i32, i32,), dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(self, "org.qtproject.Qt.QWidget", "minimumSize")
    }

    fn maximum_size(&self) -> Result<(i32, i32,), dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(self, "org.qtproject.Qt.QWidget", "maximumSize")
    }

    fn minimum_width(&self) -> Result<i32, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(self, "org.qtproject.Qt.QWidget", "minimumWidth")
    }

    fn minimum_height(&self) -> Result<i32, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(self, "org.qtproject.Qt.QWidget", "minimumHeight")
    }

    fn maximum_width(&self) -> Result<i32, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(self, "org.qtproject.Qt.QWidget", "maximumWidth")
    }

    fn maximum_height(&self) -> Result<i32, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(self, "org.qtproject.Qt.QWidget", "maximumHeight")
    }

    fn size_increment(&self) -> Result<(i32, i32,), dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(self, "org.qtproject.Qt.QWidget", "sizeIncrement")
    }

    fn base_size(&self) -> Result<(i32, i32,), dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(self, "org.qtproject.Qt.QWidget", "baseSize")
    }

    fn mouse_tracking(&self) -> Result<bool, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(self, "org.qtproject.Qt.QWidget", "mouseTracking")
    }

    fn tablet_tracking(&self) -> Result<bool, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(self, "org.qtproject.Qt.QWidget", "tabletTracking")
    }

    fn is_active_window(&self) -> Result<bool, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(self, "org.qtproject.Qt.QWidget", "isActiveWindow")
    }

    fn focus(&self) -> Result<bool, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(self, "org.qtproject.Qt.QWidget", "focus")
    }

    fn updates_enabled(&self) -> Result<bool, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(self, "org.qtproject.Qt.QWidget", "updatesEnabled")
    }

    fn visible(&self) -> Result<bool, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(self, "org.qtproject.Qt.QWidget", "visible")
    }

    fn minimized(&self) -> Result<bool, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(self, "org.qtproject.Qt.QWidget", "minimized")
    }

    fn maximized(&self) -> Result<bool, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(self, "org.qtproject.Qt.QWidget", "maximized")
    }

    fn full_screen(&self) -> Result<bool, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(self, "org.qtproject.Qt.QWidget", "fullScreen")
    }

    fn size_hint(&self) -> Result<(i32, i32,), dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(self, "org.qtproject.Qt.QWidget", "sizeHint")
    }

    fn minimum_size_hint(&self) -> Result<(i32, i32,), dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(self, "org.qtproject.Qt.QWidget", "minimumSizeHint")
    }

    fn accept_drops(&self) -> Result<bool, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(self, "org.qtproject.Qt.QWidget", "acceptDrops")
    }

    fn window_title(&self) -> Result<String, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(self, "org.qtproject.Qt.QWidget", "windowTitle")
    }

    fn window_icon_text(&self) -> Result<String, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(self, "org.qtproject.Qt.QWidget", "windowIconText")
    }

    fn window_opacity(&self) -> Result<f64, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(self, "org.qtproject.Qt.QWidget", "windowOpacity")
    }

    fn window_modified(&self) -> Result<bool, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(self, "org.qtproject.Qt.QWidget", "windowModified")
    }

    fn tool_tip(&self) -> Result<String, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(self, "org.qtproject.Qt.QWidget", "toolTip")
    }

    fn tool_tip_duration(&self) -> Result<i32, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(self, "org.qtproject.Qt.QWidget", "toolTipDuration")
    }

    fn status_tip(&self) -> Result<String, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(self, "org.qtproject.Qt.QWidget", "statusTip")
    }

    fn whats_this(&self) -> Result<String, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(self, "org.qtproject.Qt.QWidget", "whatsThis")
    }

    fn accessible_name(&self) -> Result<String, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(self, "org.qtproject.Qt.QWidget", "accessibleName")
    }

    fn accessible_description(&self) -> Result<String, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(self, "org.qtproject.Qt.QWidget", "accessibleDescription")
    }

    fn accessible_identifier(&self) -> Result<String, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(self, "org.qtproject.Qt.QWidget", "accessibleIdentifier")
    }

    fn auto_fill_background(&self) -> Result<bool, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(self, "org.qtproject.Qt.QWidget", "autoFillBackground")
    }

    fn style_sheet(&self) -> Result<String, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(self, "org.qtproject.Qt.QWidget", "styleSheet")
    }

    fn window_file_path(&self) -> Result<String, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(self, "org.qtproject.Qt.QWidget", "windowFilePath")
    }

    fn setenabled(&self, value: bool) -> Result<(), dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::set(self, "org.qtproject.Qt.QWidget", "enabled", value)
    }

    fn setgeometry(&self, value: (i32, i32, i32, i32,)) -> Result<(), dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::set(self, "org.qtproject.Qt.QWidget", "geometry", value)
    }

    fn setpos(&self, value: (i32, i32,)) -> Result<(), dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::set(self, "org.qtproject.Qt.QWidget", "pos", value)
    }

    fn setsize(&self, value: (i32, i32,)) -> Result<(), dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::set(self, "org.qtproject.Qt.QWidget", "size", value)
    }

    fn setminimum_size(&self, value: (i32, i32,)) -> Result<(), dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::set(self, "org.qtproject.Qt.QWidget", "minimumSize", value)
    }

    fn setmaximum_size(&self, value: (i32, i32,)) -> Result<(), dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::set(self, "org.qtproject.Qt.QWidget", "maximumSize", value)
    }

    fn setminimum_width(&self, value: i32) -> Result<(), dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::set(self, "org.qtproject.Qt.QWidget", "minimumWidth", value)
    }

    fn setminimum_height(&self, value: i32) -> Result<(), dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::set(self, "org.qtproject.Qt.QWidget", "minimumHeight", value)
    }

    fn setmaximum_width(&self, value: i32) -> Result<(), dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::set(self, "org.qtproject.Qt.QWidget", "maximumWidth", value)
    }

    fn setmaximum_height(&self, value: i32) -> Result<(), dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::set(self, "org.qtproject.Qt.QWidget", "maximumHeight", value)
    }

    fn setsize_increment(&self, value: (i32, i32,)) -> Result<(), dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::set(self, "org.qtproject.Qt.QWidget", "sizeIncrement", value)
    }

    fn setbase_size(&self, value: (i32, i32,)) -> Result<(), dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::set(self, "org.qtproject.Qt.QWidget", "baseSize", value)
    }

    fn setmouse_tracking(&self, value: bool) -> Result<(), dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::set(self, "org.qtproject.Qt.QWidget", "mouseTracking", value)
    }

    fn settablet_tracking(&self, value: bool) -> Result<(), dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::set(self, "org.qtproject.Qt.QWidget", "tabletTracking", value)
    }

    fn setupdates_enabled(&self, value: bool) -> Result<(), dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::set(self, "org.qtproject.Qt.QWidget", "updatesEnabled", value)
    }

    fn setvisible(&self, value: bool) -> Result<(), dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::set(self, "org.qtproject.Qt.QWidget", "visible", value)
    }

    fn setaccept_drops(&self, value: bool) -> Result<(), dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::set(self, "org.qtproject.Qt.QWidget", "acceptDrops", value)
    }

    fn setwindow_title(&self, value: String) -> Result<(), dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::set(self, "org.qtproject.Qt.QWidget", "windowTitle", value)
    }

    fn setwindow_icon_text(&self, value: String) -> Result<(), dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::set(self, "org.qtproject.Qt.QWidget", "windowIconText", value)
    }

    fn setwindow_opacity(&self, value: f64) -> Result<(), dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::set(self, "org.qtproject.Qt.QWidget", "windowOpacity", value)
    }

    fn setwindow_modified(&self, value: bool) -> Result<(), dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::set(self, "org.qtproject.Qt.QWidget", "windowModified", value)
    }

    fn settool_tip(&self, value: String) -> Result<(), dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::set(self, "org.qtproject.Qt.QWidget", "toolTip", value)
    }

    fn settool_tip_duration(&self, value: i32) -> Result<(), dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::set(self, "org.qtproject.Qt.QWidget", "toolTipDuration", value)
    }

    fn setstatus_tip(&self, value: String) -> Result<(), dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::set(self, "org.qtproject.Qt.QWidget", "statusTip", value)
    }

    fn setwhats_this(&self, value: String) -> Result<(), dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::set(self, "org.qtproject.Qt.QWidget", "whatsThis", value)
    }

    fn setaccessible_name(&self, value: String) -> Result<(), dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::set(self, "org.qtproject.Qt.QWidget", "accessibleName", value)
    }

    fn setaccessible_description(&self, value: String) -> Result<(), dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::set(self, "org.qtproject.Qt.QWidget", "accessibleDescription", value)
    }

    fn setaccessible_identifier(&self, value: String) -> Result<(), dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::set(self, "org.qtproject.Qt.QWidget", "accessibleIdentifier", value)
    }

    fn setauto_fill_background(&self, value: bool) -> Result<(), dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::set(self, "org.qtproject.Qt.QWidget", "autoFillBackground", value)
    }

    fn setstyle_sheet(&self, value: String) -> Result<(), dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::set(self, "org.qtproject.Qt.QWidget", "styleSheet", value)
    }

    fn setwindow_file_path(&self, value: String) -> Result<(), dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::set(self, "org.qtproject.Qt.QWidget", "windowFilePath", value)
    }
}

pub trait OrgKdeKMainWindow {
    fn actions(&self) -> Result<Vec<String>, dbus::Error>;
    fn activate_action(&self, action: &str) -> Result<bool, dbus::Error>;
    fn disable_action(&self, action: &str) -> Result<bool, dbus::Error>;
    fn enable_action(&self, action: &str) -> Result<bool, dbus::Error>;
    fn action_is_enabled(&self, action: &str) -> Result<bool, dbus::Error>;
    fn action_tool_tip(&self, action: &str) -> Result<String, dbus::Error>;
    fn win_id(&self) -> Result<i64, dbus::Error>;
    fn grab_window_to_clip_board(&self) -> Result<(), dbus::Error>;
}

impl<'a, T: blocking::BlockingSender, C: ::std::ops::Deref<Target=T>> OrgKdeKMainWindow for blocking::Proxy<'a, C> {

    fn actions(&self) -> Result<Vec<String>, dbus::Error> {
        self.method_call("org.kde.KMainWindow", "actions", ())
            .and_then(|r: (Vec<String>, )| Ok(r.0, ))
    }

    fn activate_action(&self, action: &str) -> Result<bool, dbus::Error> {
        self.method_call("org.kde.KMainWindow", "activateAction", (action, ))
            .and_then(|r: (bool, )| Ok(r.0, ))
    }

    fn disable_action(&self, action: &str) -> Result<bool, dbus::Error> {
        self.method_call("org.kde.KMainWindow", "disableAction", (action, ))
            .and_then(|r: (bool, )| Ok(r.0, ))
    }

    fn enable_action(&self, action: &str) -> Result<bool, dbus::Error> {
        self.method_call("org.kde.KMainWindow", "enableAction", (action, ))
            .and_then(|r: (bool, )| Ok(r.0, ))
    }

    fn action_is_enabled(&self, action: &str) -> Result<bool, dbus::Error> {
        self.method_call("org.kde.KMainWindow", "actionIsEnabled", (action, ))
            .and_then(|r: (bool, )| Ok(r.0, ))
    }

    fn action_tool_tip(&self, action: &str) -> Result<String, dbus::Error> {
        self.method_call("org.kde.KMainWindow", "actionToolTip", (action, ))
            .and_then(|r: (String, )| Ok(r.0, ))
    }

    fn win_id(&self) -> Result<i64, dbus::Error> {
        self.method_call("org.kde.KMainWindow", "winId", ())
            .and_then(|r: (i64, )| Ok(r.0, ))
    }

    fn grab_window_to_clip_board(&self) -> Result<(), dbus::Error> {
        self.method_call("org.kde.KMainWindow", "grabWindowToClipBoard", ())
    }
}

pub trait OrgFreedesktopDBusProperties {
    fn get(&self, interface_name: &str, property_name: &str) -> Result<arg::Variant<Box<dyn arg::RefArg + 'static>>, dbus::Error>;
    fn set(&self, interface_name: &str, property_name: &str, value: arg::Variant<Box<dyn arg::RefArg>>) -> Result<(), dbus::Error>;
    fn get_all(&self, interface_name: &str) -> Result<arg::PropMap, dbus::Error>;
}

#[derive(Debug)]
pub struct OrgFreedesktopDBusPropertiesPropertiesChanged {
    pub interface_name: String,
    pub changed_properties: arg::PropMap,
    pub invalidated_properties: Vec<String>,
}

impl arg::AppendAll for OrgFreedesktopDBusPropertiesPropertiesChanged {
    fn append(&self, i: &mut arg::IterAppend) {
        arg::RefArg::append(&self.interface_name, i);
        arg::RefArg::append(&self.changed_properties, i);
        arg::RefArg::append(&self.invalidated_properties, i);
    }
}

impl arg::ReadAll for OrgFreedesktopDBusPropertiesPropertiesChanged {
    fn read(i: &mut arg::Iter) -> Result<Self, arg::TypeMismatchError> {
        Ok(OrgFreedesktopDBusPropertiesPropertiesChanged {
            interface_name: i.read()?,
            changed_properties: i.read()?,
            invalidated_properties: i.read()?,
        })
    }
}

impl dbus::message::SignalArgs for OrgFreedesktopDBusPropertiesPropertiesChanged {
    const NAME: &'static str = "PropertiesChanged";
    const INTERFACE: &'static str = "org.freedesktop.DBus.Properties";
}

impl<'a, T: blocking::BlockingSender, C: ::std::ops::Deref<Target=T>> OrgFreedesktopDBusProperties for blocking::Proxy<'a, C> {

    fn get(&self, interface_name: &str, property_name: &str) -> Result<arg::Variant<Box<dyn arg::RefArg + 'static>>, dbus::Error> {
        self.method_call("org.freedesktop.DBus.Properties", "Get", (interface_name, property_name, ))
            .and_then(|r: (arg::Variant<Box<dyn arg::RefArg + 'static>>, )| Ok(r.0, ))
    }

    fn set(&self, interface_name: &str, property_name: &str, value: arg::Variant<Box<dyn arg::RefArg>>) -> Result<(), dbus::Error> {
        self.method_call("org.freedesktop.DBus.Properties", "Set", (interface_name, property_name, value, ))
    }

    fn get_all(&self, interface_name: &str) -> Result<arg::PropMap, dbus::Error> {
        self.method_call("org.freedesktop.DBus.Properties", "GetAll", (interface_name, ))
            .and_then(|r: (arg::PropMap, )| Ok(r.0, ))
    }
}

pub trait OrgFreedesktopDBusIntrospectable {
    fn introspect(&self) -> Result<String, dbus::Error>;
}

impl<'a, T: blocking::BlockingSender, C: ::std::ops::Deref<Target=T>> OrgFreedesktopDBusIntrospectable for blocking::Proxy<'a, C> {

    fn introspect(&self) -> Result<String, dbus::Error> {
        self.method_call("org.freedesktop.DBus.Introspectable", "Introspect", ())
            .and_then(|r: (String, )| Ok(r.0, ))
    }
}

pub trait OrgFreedesktopDBusPeer {
    fn ping(&self) -> Result<(), dbus::Error>;
    fn get_machine_id(&self) -> Result<String, dbus::Error>;
}

impl<'a, T: blocking::BlockingSender, C: ::std::ops::Deref<Target=T>> OrgFreedesktopDBusPeer for blocking::Proxy<'a, C> {

    fn ping(&self) -> Result<(), dbus::Error> {
        self.method_call("org.freedesktop.DBus.Peer", "Ping", ())
    }

    fn get_machine_id(&self) -> Result<String, dbus::Error> {
        self.method_call("org.freedesktop.DBus.Peer", "GetMachineId", ())
            .and_then(|r: (String, )| Ok(r.0, ))
    }
}
